service: products-service

frameworkVersion: '3.28.1'

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Get*
        - dynamodb:Scan*
        - dynamodb:PutItem
      Resource: '*'
custom:
    autoswagger:
        apiType: 'http'
        
functions:
  getProductsList:
    handler: handler.getProductsList
    environment:
      PRODUCTS_TABLE: products
      STOCKS_TABLE: stocks
    events:
      - http:
          method: get
          path: /products
          cors: true
          responseData: {
            200: {
              description: 'successful Api Response',
              bodyType: 'Product',
            },
            500: {
              description: 'An error occurred while retrieving products.',
            }
          }  

  getProductsById:
    handler: handler.getProductsById
    environment:
      PRODUCTS_TABLE: products
      STOCKS_TABLE: stocks
    events:
      - http:
          path: products/{productId}
          cors: true
          method: get
          responseData: {
            200: {
              description: 'successful Api Response',
              bodyType: 'Product',
            },
            404: {
              description: 'Product not found'
            },
            500: {
              description: 'Error getting product'
            }
          }  

  createProduct:
    handler: handler.createProduct
    environment:
      PRODUCTS_TABLE: products
      STOCKS_TABLE: stocks
    events:
      - http:
          path: products
          method: post
          cors: true
          responseData: {
            200: {
              description: 'Product created successfully',
              bodyType: 'Product',
            },
            400: {
              description: 'Error creating product, product data is invalid',
            },
            500: {
              description: 'Error creating product',
            }
          }