service: import-service

frameworkVersion: '3'

plugins:
  - serverless-webpack
  
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
        - sqs:*
      Resource:
        - arn:aws:s3:::import-service-s3bucket/
        - arn:aws:s3:::import-service-s3bucket/*
        - arn:aws:sqs:${aws:region}:${aws:accountId}:catalogItemsQueue
functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors:
            origins:
              - https://d10oh2u1zxq3h3.cloudfront.net
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - pragma
              - cache-control
            allowCredentials: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer: 
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:authorization-service-dev-basicAuthorizer
            type: token
            resultTtlInSeconds: 0
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-service-s3bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
